version: '2'
services:
  front:
    container_name: test.front
    image: node:18
    ports:
      - '3000:3000'
    volumes:
      - ./front:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'npm start'
  back:
    container_name: test.back
    image: ertfly/php8.1-apache-buster
    restart: always
    ports:
      - '8030:80'
    volumes:
      - ./back:/app
    networks:
      - test-net
      
networks:
  test-net:
    external: true