version: '2'
services:
  front:
    container_name: test.front
    image: ertfly/php8.1-apache-buster
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./front/build:/app/public
    networks:
      - test-net
  back:
    container_name: test.back
    image: ertfly/php8.1-apache-buster
    restart: always
    ports:
      - '8030:80'
    volumes:
      - ./back:/app
    networks:
      - test-net
      
networks:
  test-net:
    external: true